### ISSUE TITLE
the patch_size  of  the input HSI cube 

### ISSUE THREAD

**Issue by HopePersist** [mhaut/DeepNRD#1]
hello, when i run your code, according to your letter, ‘input patch size of 11 × 11’. However, depending on the network structure and parameters, the size of the input data is at least 23. i am confused about this.
Could you explain that ? thank you . 
Looking forward to your reply.

**Comment by mhaut** [comment]
Hello zhuwenxaing,

Sorry for the mistake, the correct input size is 23x23x1

Your sincerely.

**Comment by HopePersist** [comment]
OK. thank you!

**Comment by mhaut** [comment]
You are very welcome.
